POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "A Blog Post",
    "author": "Ada Lovelace",
    "url": "/api/blog/posts",
    "likes": 0,
    "userId": "6abbd44e6688c6feb480a693"
}

###
GET http://localhost:3003/api/blogs
